const { StyleSheet } = require("react-native");

export const style=StyleSheet.create({
    cbox:{flexDirection:'column',justifyContent:'center',alignItems:'center'},
    cprev:{width:'100%',height:'8%',backgroundColor:'white'},
    cImg:{height:40,width:40,marginHorizontal:10,marginVertical:5},
    cheading:{fontSize:25,fontWeight:'bold',color:'black',marginTop:20},
    cmatchType:{flexDirection:'row',marginHorizontal:5,marginTop:10},
    cmatchHeading:{fontSize:20,fontWeight:'bold',marginVertical:10,marginRight:4},
    cdropdown:{width:'60%'},
    cInpDesign:{flexDirection:'row',marginHorizontal:5,marginTop:40},
    cplaceholder:{fontSize:20,fontWeight:'bold',marginVertical:10,marginRight:69},
    inpBox:{width:'60%'},
    ctxtInput:{borderWidth:1,borderRadius:10},
    chead:{fontSize:20,fontWeight:'bold',marginVertical:10,marginRight:14},
    cborder:{borderWidth:1,borderRadius:10,width:'60%'},
    time:{flexDirection:'row'},
    timeImg:{height:30,width:30,marginVertical:10,marginHorizontal:5},
    cdate:{marginVertical:14,marginHorizontal:5},
    ctime:{marginVertical:14,marginHorizontal:2},
    cgrndText:{fontSize:20,fontWeight:'bold',marginVertical:10,marginRight:45},
    cBtnDesign:{backgroundColor:'#367545',marginVertical:20,borderRadius:10},
    scheduleText:{color:'white',fontSize:20,fontWeight:'bold',paddingVertical:10,paddingHorizontal:135},
    mBox:{width:'100%',height:'7%',backgroundColor:'white'},
    mprev:{height:40,width:40,marginHorizontal:10,marginVertical:8},
    mheader:{textAlign:'center',fontSize:25,fontWeight:'bold'},
    mSubBox:{flexDirection:'column',borderWidth:1,borderRadius:10,justifyContent:'center',alignItems:'center',marginTop:30,marginHorizontal:30},
    mteamText:{fontSize:20,fontWeight:'bold'},
    mShow:{backgroundColor:'#367545',marginVertical:10,borderRadius:10},
    mBtnText:{color:'white',fontSize:20,fontWeight:'bold',paddingVertical:10,paddingHorizontal:90},
    mmBtnText:{color:'white',fontSize:20,fontWeight:'bold',paddingVertical:10,paddingHorizontal:84},
    modalDesign:{flexDirection:'column',justifyContent:'center',alignItems:'center',marginTop:50},
    team:{fontSize:18,fontWeight:'bold'},
    mbtn:{backgroundColor:'#367545',marginVertical:20,borderRadius:10},
    modalBtnText:{color:'white',fontSize:20,fontWeight:'bold',paddingVertical:10,paddingHorizontal:135},
    rbox:{flexDirection:"column",justifyContent:'center',alignItems:'center'},
    rprev:{width:'100%',height:60,backgroundColor:'white'},
    rImg:{height:40,width:40,marginHorizontal:10,marginVertical:5},
    rdetails:{fontSize:25,fontWeight:'bold',marginTop:20},
    

})